//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func euler() -> Int {
    
    var fibonnaci = [2,1]
    repeat {
        let newElement = fibonnaci[0] + fibonnaci[1]
        if newElement <= 4000000 {
             fibonnaci.insert(newElement, at: 0)
        } else {
            break
        }
       
    } while fibonnaci[0] <= 4000000
    print(fibonnaci)
    return fibonnaci.filter { $0.isMultiple(of: 2) }.reduce(0, +)
}
euler()
